### ISSUE TITLE
I get Error when I run the project

### ISSUE THREAD

**Issue by shaghayegh70** [THEOplayer/android-tv-sdk-starter-project#2]
Hi 
I downloaded and opened the project in android studio , it build successfully but when I run it I get this error:

Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Failed to transform theoplayer.aar to match attributes {artifactType=android-databinding}.
      > Execution failed for JetifyTransform: D:\AndroidTV\android-tv-sdk-starter-project-master\app\libs\theoplayer.aar.
         > Transform's input file does not exist: D:\AndroidTV\android-tv-sdk-starter-project-master\app\libs\theoplayer.aar.

**Comment by thijsl** [comment]
Were you able to resolve this, @shaghayegh70 ?

**Comment by ceyhun-o** [comment]
Closing as stale.
